# Generated by Django 6.0.5 on 2026-05-30 13:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='المعرف الفريد (UUID)', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='البريد الإلكتروني', max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, help_text='اسم المستخدم', max_length=150, unique=True)),
                ('password', models.CharField(help_text='كلمة المرور (مشفرة)', max_length=128)),
                ('person_name', models.CharField(help_text='الاسم الشخصي', max_length=255)),
                ('last_name', models.CharField(help_text='اسم العائلة', max_length=255)),
                ('phone', models.CharField(help_text='رقم الهاتف', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('admin', 'مدير'), ('user', 'مستخدم'), ('moderator', 'مشرف'), ('owner', 'مالك')], db_index=True, default='user', help_text='نوع المستخدم (مدير، مستخدم، مشرف، مالك)', max_length=20)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('banned', 'محظور'), ('suspended', 'معلق')], db_index=True, default='active', help_text='حالة المستخدم (نشط، غير نشط، محظور، معلق)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاريخ آخر تحديث')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='تاريخ الحذف', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='المستخدم الذي قام بإنشاء هذا الحساب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, help_text='آخر مستخدم قام بتعديل هذا الحساب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_updated', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمين',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='users_email_f7aa6a_idx'), models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['role', 'status'], name='users_role_bc23be_idx'), models.Index(fields=['-created_at'], name='users_created_30b417_idx'), models.Index(fields=['phone'], name='users_phone_af6883_idx')],
            },
        ),
    ]
